CREATE TABLE `order` (
id	int(11) NOT NULL,
AmazonOrderId	varchar(150) DEFAULT NULL,
SellerOrderId	varchar(150) DEFAULT NULL,
PurchaseDate	varchar(150) DEFAULT NULL,
LastUpdateDate	varchar(150) DEFAULT NULL,
OrderStatus	varchar(150) DEFAULT NULL,
FulfillmentChannel	varchar(150) DEFAULT NULL,
SalesChannel	varchar(150) DEFAULT NULL,
OrderChannel	varchar(150) DEFAULT NULL,
ShipServiceLevel	varchar(150) DEFAULT NULL,
OrderTotal	varchar(150) DEFAULT NULL,
NumberOfItemsShipped	varchar(150) DEFAULT NULL,
NumberOfItemsUnshipped	varchar(150) DEFAULT NULL,
PaymentExecutionDetail	varchar(150) DEFAULT NULL,
PaymentMethod	varchar(150) DEFAULT NULL,
PaymentMethodDetails	varchar(150) DEFAULT NULL,
MarketplaceId	varchar(150) DEFAULT NULL,
ShipmentServiceLevelCategory	varchar(150) DEFAULT NULL,
EasyShipShipmentStatus	varchar(150) DEFAULT NULL,
CbaDisplayableShippingLabel	varchar(150) DEFAULT NULL,
OrderType	varchar(150) DEFAULT NULL,
EarliestShipDate	varchar(150) DEFAULT NULL,
LatestShipDate	varchar(150) DEFAULT NULL,
EarliestDeliveryDate	datetime DEFAULT NULL,
LatestDeliveryDate	datetime DEFAULT NULL,
IsBusinessOrder	varchar(150) DEFAULT NULL,
IsPrime	varchar(150) DEFAULT NULL,
IsPremiumOrder	varchar(150) DEFAULT NULL,
IsGlobalExpressEnabled	varchar(150) DEFAULT NULL,
ReplacedOrderId	varchar(150) DEFAULT NULL,
IsReplacementOrder	varchar(150) DEFAULT NULL,
PromiseResponseDueDate	datetime DEFAULT NULL,
IsEstimatedShipDateSet	datetime DEFAULT NULL,
IsSoldByAB	varchar(150) DEFAULT NULL,
DefaultShipFromLocationAddress	varchar(150) DEFAULT NULL,
FulfillmentInstruction	varchar(150) DEFAULT NULL,
IsISPU	varchar(150) DEFAULT NULL,	
created	 datetime DEFAULT NULL,
modified datetime DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `order`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `AmazonOrderId` (`AmazonOrderId`),
  ADD KEY `index_sku` (`AmazonOrderId`);
ALTER TABLE `order`
  CHANGE  `id` INT(11) NOT NULL AUTO_INCREMENT;
COMMIT;

CREATE TABLE `order_item` (
id	int(11) NOT NULL,
order_id int(11) DEFAULT NULL,
ASIN	varchar(150) DEFAULT NULL,
SellerSKU	varchar(150) DEFAULT NULL,
OrderItemId	varchar(150) DEFAULT NULL,
Title	varchar(150) DEFAULT NULL,
QuantityOrdered	varchar(150) DEFAULT NULL,
QuantityShipped	varchar(150) DEFAULT NULL,
ProductInfo	varchar(150) DEFAULT NULL,
PointsGranted	varchar(150) DEFAULT NULL,
ItemPrice	varchar(150) DEFAULT NULL,
ShippingPrice	varchar(150) DEFAULT NULL,
ItemTax	varchar(150) DEFAULT NULL,
ShippingTax	varchar(150) DEFAULT NULL,
ShippingDiscount	varchar(150) DEFAULT NULL,
ShippingDiscountTax	varchar(150) DEFAULT NULL,
PromotionDiscount	varchar(150) DEFAULT NULL,
PromotionDiscountTax	varchar(150) DEFAULT NULL,
PromotionIds	varchar(150) DEFAULT NULL,
CODFee	varchar(150) DEFAULT NULL,
CODFeeDiscount	varchar(150) DEFAULT NULL,
IsGift	varchar(150) DEFAULT NULL,
ConditionNote	varchar(150) DEFAULT NULL,
ConditionId	varchar(150) DEFAULT NULL,
ConditionSubtypeId	varchar(150) DEFAULT NULL,
ScheduledDeliveryStartDate	varchar(150) DEFAULT NULL,
ScheduledDeliveryEndDate	varchar(150) DEFAULT NULL,
PriceDesignation	varchar(150) DEFAULT NULL,
TaxCollection	varchar(150) DEFAULT NULL,
SerialNumberRequired	varchar(150) DEFAULT NULL,
IsTransparency	varchar(150) DEFAULT NULL,
IossNumber	varchar(150) DEFAULT NULL,
StoreChainStoreId	varchar(150) DEFAULT NULL,
DeemedResellerCategory	varchar(150) DEFAULT NULL,
created	 datetime DEFAULT NULL,
modified datetime DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `order_item` ADD PRIMARY KEY(`id`);

ALTER TABLE `order_item` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT;